from PyQt5 import QtCore, QtWidgets


class Ui_RaBitViewer(object):
    def setupUi(self, RaBitViewer):
        RaBitViewer.setObjectName("RaBitViewer")
        RaBitViewer.resize(1500, 600)
        RaBitViewer.setMaximumSize(QtCore.QSize(1600, 600))
        self.centralwidget = QtWidgets.QWidget(RaBitViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 58, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 20, 58, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(500, 370, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 360, 71, 41))
        self.pushButton.setObjectName("pushButton")

        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(90, 40, 111, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(210, 40, 111, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(330, 40, 111, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(90, 60, 111, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(210, 60, 111, 22))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(330, 60, 111, 22))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(90, 80, 111, 22))
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.horizontalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(210, 80, 111, 22))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalSlider_9 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(330, 80, 111, 22))
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalSlider_10 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(90, 100, 111, 22))
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(210, 100, 111, 22))
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.horizontalSlider_12 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(330, 100, 111, 22))
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(90, 120, 111, 22))
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(210, 120, 111, 22))
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.horizontalSlider_15 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(330, 120, 111, 22))
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.horizontalSlider_16 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_16.setGeometry(QtCore.QRect(90, 140, 111, 22))
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setObjectName("horizontalSlider_16")
        self.horizontalSlider_17 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_17.setGeometry(QtCore.QRect(210, 140, 111, 22))
        self.horizontalSlider_17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_17.setObjectName("horizontalSlider_17")
        self.horizontalSlider_18 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_18.setGeometry(QtCore.QRect(330, 140, 111, 22))
        self.horizontalSlider_18.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_18.setObjectName("horizontalSlider_18")
        self.horizontalSlider_19 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_19.setGeometry(QtCore.QRect(90, 160, 111, 22))
        self.horizontalSlider_19.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_19.setObjectName("horizontalSlider_19")
        self.horizontalSlider_20 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_20.setGeometry(QtCore.QRect(210, 160, 111, 22))
        self.horizontalSlider_20.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_20.setObjectName("horizontalSlider_20")
        self.horizontalSlider_21 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_21.setGeometry(QtCore.QRect(330, 160, 111, 22))
        self.horizontalSlider_21.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_21.setObjectName("horizontalSlider_21")
        self.horizontalSlider_22 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_22.setGeometry(QtCore.QRect(90, 180, 111, 22))
        self.horizontalSlider_22.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_22.setObjectName("horizontalSlider_22")
        self.horizontalSlider_23 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_23.setGeometry(QtCore.QRect(210, 180, 111, 22))
        self.horizontalSlider_23.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_23.setObjectName("horizontalSlider_23")
        self.horizontalSlider_24 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_24.setGeometry(QtCore.QRect(330, 180, 111, 22))
        self.horizontalSlider_24.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_24.setObjectName("horizontalSlider_24")
        self.horizontalSlider_25 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_25.setGeometry(QtCore.QRect(90, 200, 111, 22))
        self.horizontalSlider_25.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_25.setObjectName("horizontalSlider_25")
        self.horizontalSlider_26 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_26.setGeometry(QtCore.QRect(210, 200, 111, 22))
        self.horizontalSlider_26.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_26.setObjectName("horizontalSlider_26")
        self.horizontalSlider_27 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_27.setGeometry(QtCore.QRect(330, 200, 111, 22))
        self.horizontalSlider_27.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_27.setObjectName("horizontalSlider_27")
        self.horizontalSlider_28 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_28.setGeometry(QtCore.QRect(90, 220, 111, 22))
        self.horizontalSlider_28.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_28.setObjectName("horizontalSlider_28")
        self.horizontalSlider_29 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_29.setGeometry(QtCore.QRect(210, 220, 111, 22))
        self.horizontalSlider_29.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_29.setObjectName("horizontalSlider_29")
        self.horizontalSlider_30 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_30.setGeometry(QtCore.QRect(330, 220, 111, 22))
        self.horizontalSlider_30.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_30.setObjectName("horizontalSlider_30")
        self.horizontalSlider_31 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_31.setGeometry(QtCore.QRect(90, 240, 111, 22))
        self.horizontalSlider_31.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_31.setObjectName("horizontalSlider_31")
        self.horizontalSlider_32 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_32.setGeometry(QtCore.QRect(210, 240, 111, 22))
        self.horizontalSlider_32.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_32.setObjectName("horizontalSlider_32")
        self.horizontalSlider_33 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_33.setGeometry(QtCore.QRect(330, 240, 111, 22))
        self.horizontalSlider_33.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_33.setObjectName("horizontalSlider_33")
        self.horizontalSlider_34 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_34.setGeometry(QtCore.QRect(90, 260, 111, 22))
        self.horizontalSlider_34.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_34.setObjectName("horizontalSlider_34")
        self.horizontalSlider_35 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_35.setGeometry(QtCore.QRect(210, 260, 111, 22))
        self.horizontalSlider_35.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_35.setObjectName("horizontalSlider_35")
        self.horizontalSlider_36 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_36.setGeometry(QtCore.QRect(330, 260, 111, 22))
        self.horizontalSlider_36.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_36.setObjectName("horizontalSlider_36")
        self.horizontalSlider_37 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_37.setGeometry(QtCore.QRect(90, 280, 111, 22))
        self.horizontalSlider_37.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_37.setObjectName("horizontalSlider_37")
        self.horizontalSlider_38 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_38.setGeometry(QtCore.QRect(210, 280, 111, 22))
        self.horizontalSlider_38.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_38.setObjectName("horizontalSlider_38")
        self.horizontalSlider_39 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_39.setGeometry(QtCore.QRect(330, 280, 111, 22))
        self.horizontalSlider_39.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_39.setObjectName("horizontalSlider_39")
        self.horizontalSlider_40 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_40.setGeometry(QtCore.QRect(90, 300, 111, 22))
        self.horizontalSlider_40.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_40.setObjectName("horizontalSlider_40")
        self.horizontalSlider_41 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_41.setGeometry(QtCore.QRect(210, 300, 111, 22))
        self.horizontalSlider_41.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_41.setObjectName("horizontalSlider_41")
        self.horizontalSlider_42 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_42.setGeometry(QtCore.QRect(330, 300, 111, 22))
        self.horizontalSlider_42.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_42.setObjectName("horizontalSlider_42")
        self.horizontalSlider_43 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_43.setGeometry(QtCore.QRect(90, 320, 111, 22))
        self.horizontalSlider_43.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_43.setObjectName("horizontalSlider_43")
        self.horizontalSlider_44 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_44.setGeometry(QtCore.QRect(210, 320, 111, 22))
        self.horizontalSlider_44.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_44.setObjectName("horizontalSlider_44")
        self.horizontalSlider_45 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_45.setGeometry(QtCore.QRect(330, 320, 111, 22))
        self.horizontalSlider_45.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_45.setObjectName("horizontalSlider_45")
        self.horizontalSlider_46 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_46.setGeometry(QtCore.QRect(90, 340, 111, 22))
        self.horizontalSlider_46.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_46.setObjectName("horizontalSlider_46")
        self.horizontalSlider_47 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_47.setGeometry(QtCore.QRect(210, 340, 111, 22))
        self.horizontalSlider_47.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_47.setObjectName("horizontalSlider_47")
        self.horizontalSlider_48 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_48.setGeometry(QtCore.QRect(330, 340, 111, 22))
        self.horizontalSlider_48.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_48.setObjectName("horizontalSlider_48")
        self.horizontalSlider_49 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_49.setGeometry(QtCore.QRect(90, 360, 111, 22))
        self.horizontalSlider_49.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_49.setObjectName("horizontalSlider_49")
        self.horizontalSlider_50 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_50.setGeometry(QtCore.QRect(210, 360, 111, 22))
        self.horizontalSlider_50.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_50.setObjectName("horizontalSlider_50")
        self.horizontalSlider_51 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_51.setGeometry(QtCore.QRect(330, 360, 111, 22))
        self.horizontalSlider_51.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_51.setObjectName("horizontalSlider_51")
        self.horizontalSlider_52 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_52.setGeometry(QtCore.QRect(90, 380, 111, 22))
        self.horizontalSlider_52.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_52.setObjectName("horizontalSlider_52")
        self.horizontalSlider_53 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_53.setGeometry(QtCore.QRect(210, 380, 111, 22))
        self.horizontalSlider_53.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_53.setObjectName("horizontalSlider_53")
        self.horizontalSlider_54 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_54.setGeometry(QtCore.QRect(330, 380, 111, 22))
        self.horizontalSlider_54.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_54.setObjectName("horizontalSlider_54")
        self.horizontalSlider_55 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_55.setGeometry(QtCore.QRect(90, 400, 111, 22))
        self.horizontalSlider_55.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_55.setObjectName("horizontalSlider_55")
        self.horizontalSlider_56 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_56.setGeometry(QtCore.QRect(210, 400, 111, 22))
        self.horizontalSlider_56.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_56.setObjectName("horizontalSlider_56")
        self.horizontalSlider_57 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_57.setGeometry(QtCore.QRect(330, 400, 111, 22))
        self.horizontalSlider_57.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_57.setObjectName("horizontalSlider_57")
        self.horizontalSlider_58 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_58.setGeometry(QtCore.QRect(90, 420, 111, 22))
        self.horizontalSlider_58.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_58.setObjectName("horizontalSlider_58")
        self.horizontalSlider_59 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_59.setGeometry(QtCore.QRect(210, 420, 111, 22))
        self.horizontalSlider_59.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_59.setObjectName("horizontalSlider_59")
        self.horizontalSlider_60 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_60.setGeometry(QtCore.QRect(330, 420, 111, 22))
        self.horizontalSlider_60.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_60.setObjectName("horizontalSlider_60")
        self.horizontalSlider_61 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_61.setGeometry(QtCore.QRect(90, 440, 111, 22))
        self.horizontalSlider_61.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_61.setObjectName("horizontalSlider_61")
        self.horizontalSlider_62 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_62.setGeometry(QtCore.QRect(210, 440, 111, 22))
        self.horizontalSlider_62.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_62.setObjectName("horizontalSlider_62")
        self.horizontalSlider_63 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_63.setGeometry(QtCore.QRect(330, 440, 111, 22))
        self.horizontalSlider_63.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_63.setObjectName("horizontalSlider_63")
        self.horizontalSlider_64 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_64.setGeometry(QtCore.QRect(90, 460, 111, 22))
        self.horizontalSlider_64.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_64.setObjectName("horizontalSlider_64")
        self.horizontalSlider_65 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_65.setGeometry(QtCore.QRect(210, 460, 111, 22))
        self.horizontalSlider_65.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_65.setObjectName("horizontalSlider_65")
        self.horizontalSlider_66 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_66.setGeometry(QtCore.QRect(330, 460, 111, 22))
        self.horizontalSlider_66.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_66.setObjectName("horizontalSlider_66")
        self.horizontalSlider_67 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_67.setGeometry(QtCore.QRect(90, 480, 111, 22))
        self.horizontalSlider_67.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_67.setObjectName("horizontalSlider_67")
        self.horizontalSlider_68 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_68.setGeometry(QtCore.QRect(210, 480, 111, 22))
        self.horizontalSlider_68.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_68.setObjectName("horizontalSlider_68")
        self.horizontalSlider_69 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_69.setGeometry(QtCore.QRect(330, 480, 111, 22))
        self.horizontalSlider_69.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_69.setObjectName("horizontalSlider_69")
        # self.horizontalSlider_70 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_70.setGeometry(QtCore.QRect(90, 500, 111, 22))
        # self.horizontalSlider_70.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_70.setObjectName("horizontalSlider_70")
        # self.horizontalSlider_71 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_71.setGeometry(QtCore.QRect(210, 500, 111, 22))
        # self.horizontalSlider_71.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_71.setObjectName("horizontalSlider_71")
        # self.horizontalSlider_72 = QtWidgets.QSlider(self.centralwidget)
        # self.horizontalSlider_72.setGeometry(QtCore.QRect(330, 500, 111, 22))
        # self.horizontalSlider_72.setOrientation(QtCore.Qt.Horizontal)
        # self.horizontalSlider_72.setObjectName("horizontalSlider_72")
        self.horizontalSlider_x = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_x.setGeometry(QtCore.QRect(90, 520, 333, 22))
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setObjectName("horizontalSlider_x")

        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(510, 60, 21, 131))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(550, 60, 21, 131))
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setGeometry(QtCore.QRect(590, 60, 21, 131))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.verticalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_4.setGeometry(QtCore.QRect(630, 60, 21, 131))
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.verticalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_5.setGeometry(QtCore.QRect(670, 60, 21, 131))
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.verticalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_6.setGeometry(QtCore.QRect(510, 220, 21, 131))
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.verticalSlider_7 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_7.setGeometry(QtCore.QRect(550, 220, 21, 131))
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.verticalSlider_8 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_8.setGeometry(QtCore.QRect(590, 220, 21, 131))
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.verticalSlider_9 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_9.setGeometry(QtCore.QRect(630, 220, 21, 131))
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.verticalSlider_10 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_10.setGeometry(QtCore.QRect(670, 220, 21, 131))
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        # Widget
        self.openGLWidget.setGeometry(QtCore.QRect(770, 50, 700, 500))
        self.openGLWidget.setObjectName("openGLWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(770, 20, 58, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 78, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 78, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 78, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 78, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 78, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 78, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 78, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 78, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 78, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 220, 78, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 240, 78, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 260, 78, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 280, 78, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 300, 78, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 320, 78, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 340, 78, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(10, 360, 78, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 380, 78, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(10, 400, 78, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 420, 78, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 440, 78, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 460, 78, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 480, 78, 21))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(960, 400, 78, 21))
        self.label_28.setObjectName("label_28")

        #TODO:
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setGeometry(QtCore.QRect(10, 520, 78, 21))
        self.label_x.setObjectName("label_x")

        RaBitViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RaBitViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        RaBitViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RaBitViewer)
        self.statusbar.setObjectName("statusbar")
        RaBitViewer.setStatusBar(self.statusbar)

        self.retranslateUi(RaBitViewer)
        QtCore.QMetaObject.connectSlotsByName(RaBitViewer)

    def retranslateUi(self, RaBitViewer):
        _translate = QtCore.QCoreApplication.translate
        RaBitViewer.setWindowTitle(_translate("RaBitViewer", "RaBit Viewer"))
        self.label.setText(_translate("RaBitViewer", "Pose "))
        self.label_2.setText(_translate("RaBitViewer", "Shape"))
        self.lineEdit.setText(_translate("RaBitViewer", "output.ply"))
        self.pushButton.setText(_translate("RaBitViewer", "save"))
        self.label_3.setText(_translate("RaBitViewer", "Viewer"))
        self.label_4.setText(_translate("RaBitViewer", "RootNode"))
        self.label_5.setText(_translate("RaBitViewer", "Hips"))
        self.label_6.setText(_translate("RaBitViewer", "Spine"))
        self.label_7.setText(_translate("RaBitViewer", "Spine1"))
        self.label_8.setText(_translate("RaBitViewer", "Spine2"))
        self.label_9.setText(_translate("RaBitViewer", "L_Shoulder"))
        self.label_10.setText(_translate("RaBitViewer", "L_Arm"))
        self.label_11.setText(_translate("RaBitViewer", "L_ForeArm"))
        self.label_12.setText(_translate("RaBitViewer", "L_Hand"))
        self.label_13.setText(_translate("RaBitViewer", "Neck"))
        self.label_14.setText(_translate("RaBitViewer", "Head"))
        self.label_15.setText(_translate("RaBitViewer", "L_UpLeg"))
        self.label_16.setText(_translate("RaBitViewer", "R_UpLeg"))
        self.label_17.setText(_translate("RaBitViewer", "L_Leg"))
        self.label_18.setText(_translate("RaBitViewer", "L_Foot"))
        self.label_19.setText(_translate("RaBitViewer", "L_ToeBase"))
        self.label_20.setText(_translate("RaBitViewer", "R_Shoulder"))
        self.label_21.setText(_translate("RaBitViewer", "R_Arm"))
        self.label_22.setText(_translate("RaBitViewer", "R_ForeArm"))
        self.label_23.setText(_translate("RaBitViewer", "R_Hand"))
        self.label_24.setText(_translate("RaBitViewer", "R_Leg"))
        self.label_25.setText(_translate("RaBitViewer", "R_Foot"))
        self.label_26.setText(_translate("RaBitViewer", "R_ToeBase"))
        self.label_x.setText(_translate("RaBitViewer", "View"))
